// Generated by CoffeeScript 1.6.2
(function() {
  var albumQuery, bgCol, fgCol, fix, font, fontBold, kColours, loadAssets, mm2pt, nAmerica, pageSize, pageSizes, pw, _ref, _ref1, _ref2;

  kColours = function(imgTag, opts) {
    var almostOne, attempt, bDiff, canvas, ctx, distSq, dupe, gDiff, height, i, mean, means, minDistSq, nearestMean, offset, pixelArr, prevMean, rDiff, randInt, sample, samples, width, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _len5, _m, _n, _o, _p, _q, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _results;

    if (opts == null) {
      opts = {};
    }
    if ((_ref = opts.k) == null) {
      opts.k = 3;
    }
    if ((_ref1 = opts.numSamples) == null) {
      opts.numSamples = 250;
    }
    if ((_ref2 = opts.sampleAttempts) == null) {
      opts.sampleAttempts = opts.numSamples / 2;
    }
    if ((_ref3 = opts.iterations) == null) {
      opts.iterations = 100;
    }
    if (opts.rngSeed != null) {
      Math.seedrandom(opts.rngSeed);
    }
    almostOne = 0.999999999999;
    randInt = function(lt) {
      return Math.floor(Math.random() * almostOne * lt);
    };
    width = imgTag.width, height = imgTag.height;
    canvas = make({
      tag: 'canvas',
      width: width,
      height: height
    });
    ctx = canvas.getContext('2d');
    ctx.drawImage(imgTag, 0, 0);
    pixelArr = (ctx.getImageData(0, 0, width, height)).data;
    samples = (function() {
      var _i, _ref4, _results;

      _results = [];
      for (i = _i = 0, _ref4 = opts.numSamples; 0 <= _ref4 ? _i < _ref4 : _i > _ref4; i = 0 <= _ref4 ? ++_i : --_i) {
        offset = randInt(width * height) * 4;
        _results.push({
          r: pixelArr[offset],
          g: pixelArr[offset + 1],
          b: pixelArr[offset + 2]
        });
      }
      return _results;
    })();
    means = [];
    for (i = _i = 0, _ref4 = opts.k; 0 <= _ref4 ? _i < _ref4 : _i > _ref4; i = 0 <= _ref4 ? ++_i : --_i) {
      for (attempt = _j = 0, _ref5 = opts.sampleAttempts; 0 <= _ref5 ? _j < _ref5 : _j > _ref5; attempt = 0 <= _ref5 ? ++_j : --_j) {
        dupe = false;
        mean = samples[randInt(opts.numSamples)];
        for (_k = 0, _len = means.length; _k < _len; _k++) {
          prevMean = means[_k];
          dupe = mean.r === prevMean.r && mean.g === prevMean.g && mean.b === prevMean.b;
          if (dupe) {
            break;
          }
        }
        if (!dupe) {
          break;
        }
      }
      if (dupe) {
        break;
      }
      means.push(mean);
    }
    for (i = _l = 0, _ref6 = opts.iterations; 0 <= _ref6 ? _l < _ref6 : _l > _ref6; i = 0 <= _ref6 ? ++_l : --_l) {
      for (_m = 0, _len1 = means.length; _m < _len1; _m++) {
        mean = means[_m];
        mean.sampleCount = mean.rSum = mean.gSum = mean.bSum = 0;
      }
      for (_n = 0, _len2 = samples.length; _n < _len2; _n++) {
        sample = samples[_n];
        minDistSq = Infinity;
        for (_o = 0, _len3 = means.length; _o < _len3; _o++) {
          mean = means[_o];
          rDiff = sample.r - mean.r;
          gDiff = sample.g - mean.g;
          bDiff = sample.b - mean.b;
          distSq = rDiff * rDiff + gDiff * gDiff + bDiff * bDiff;
          if (distSq < minDistSq) {
            nearestMean = mean;
            minDistSq = distSq;
          }
        }
        nearestMean.sampleCount += 1;
        nearestMean.rSum += sample.r;
        nearestMean.gSum += sample.g;
        nearestMean.bSum += sample.b;
      }
      for (_p = 0, _len4 = means.length; _p < _len4; _p++) {
        mean = means[_p];
        if (!(mean.sampleCount > 0)) {
          continue;
        }
        mean.r = mean.rSum / mean.sampleCount;
        mean.g = mean.gSum / mean.sampleCount;
        mean.b = mean.bSum / mean.sampleCount;
      }
    }
    means.sort(function(a, b) {
      return a.sampleCount < b.sampleCount;
    });
    _results = [];
    for (_q = 0, _len5 = means.length; _q < _len5; _q++) {
      mean = means[_q];
      _results.push({
        r: Math.round(mean.r),
        g: Math.round(mean.g),
        b: Math.round(mean.b)
      });
    }
    return _results;
  };

  pageSizes = {
    a4: {
      w: 595,
      h: 842
    },
    letter: {
      w: 8.5 * 72,
      h: 11 * 72
    }
  };

  nAmerica = (_ref = (_ref1 = google.loader.ClientLocation) != null ? (_ref2 = _ref1.address) != null ? _ref2.country_code : void 0 : void 0) === 'US' || _ref === 'CA';

  pageSize = pageSizes[nAmerica ? 'letter' : 'a4'];

  bgCol = [0.9, 0.9, 0.9];

  fgCol = [0.2, 0.2, 0.2];

  if (true) {
    font = 'Helvetica';
    fontBold = 'Helvetica-Bold';
  } else {
    font = 'Times-Roman';
    fontBold = 'Times-Bold';
  }

  fix = function(n) {
    return n.toFixed(3).replace(/\.?0+$/, '');
  };

  mm2pt = function(mm) {
    return mm / 25.4 * 72;
  };

  albumQuery = 'http://ws.audioscrobbler.com/2.0/?' + 'api_key=2113885e020cefe1d72f95d8378d32c1&method=album.getinfo&format=json&callback=<cb>&' + location.search.substring(1);

  loadAssets = function() {
    xhr({
      url: 'template.pdf',
      type: 'arraybuffer',
      success: function(req) {
        return pw.done({
          pdf: req.response
        });
      }
    });
    return jsonp({
      url: albumQuery,
      success: function(albumData) {
        var img, imgUrl, imgs, size, _i, _j, _len, _len1, _ref3, _ref4;

        console.log(albumData);
        imgs = {};
        _ref3 = albumData.album.image;
        for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
          img = _ref3[_i];
          imgs[img.size] = img['#text'];
        }
        _ref4 = w('mega extralarge large medium small');
        for (_j = 0, _len1 = _ref4.length; _j < _len1; _j++) {
          size = _ref4[_j];
          imgUrl = imgs[size];
          if (imgUrl != null) {
            break;
          }
        }
        return PDFImage.xhr({
          url: imgUrl.replace(/^http:\//, 'http://mackerron.com'),
          success: function(img) {
            return pw.done({
              albumData: albumData,
              img: img
            });
          }
        });
      }
    });
  };

  pw = new ParallelWaiter(2, function(data) {
    var albumName, artist, artistFlow, artistPara, backContent, c, cs, div, dur, durFlow, durMatch, durMaxWidth, durRe, filename, fontBoldObj, fontObj, frontContent, height, i, imgObj, insideFlow, insidePara, insideSize, insideText, k, maxSpineWidth, maxTrackHeight, maxTrackWidth, mediaBox, mins, name, nameFlow, namePara, num, numAndDurSize, numFlow, numMatch, numMaxWidth, numRe, pdf, releaseStr, releasedate, s, secs, spineCommands, spineSize, spineSpace, spineXHeightFactor, t, totalWidth, track, trackCommands, trackData, trackSize, trackSpacing, trackText, tracks, v, _i, _j, _k, _l, _len, _len1, _len2, _m, _ref3, _ref4;

    pdf = new HackDoc(data.pdf);
    cs = kColours(data.img.tag, {
      rngSeed: 'cdca.se.'
    });
    console.log(cs);
    for (_i = 0, _len = cs.length; _i < _len; _i++) {
      c = cs[_i];
      div = make({
        parent: get({
          tag: 'body'
        })
      });
      s = div.style;
      s.float = 'left';
      s.width = s.height = '100px';
      s.backgroundColor = "rgb(" + c.r + ", " + c.g + ", " + c.b + ")";
    }
    div = make({
      parent: get({
        tag: 'body'
      })
    });
    div.style.clear = 'both';
    imgObj = PDFImage.create(pdf, extend(data.img, {
      ignoreTransparency: true
    }));
    _ref3 = data.albumData.album, artist = _ref3.artist, albumName = _ref3.name, releasedate = _ref3.releasedate;
    tracks = (function() {
      var _j, _len1, _ref4, _results;

      _ref4 = data.albumData.album.tracks.track;
      _results = [];
      for (i = _j = 0, _len1 = _ref4.length; _j < _len1; i = ++_j) {
        t = _ref4[i];
        mins = '' + Math.floor(t.duration / 60);
        secs = '' + t.duration % 60;
        if (secs.length < 2) {
          secs = '0' + secs;
        }
        _results.push("" + (i + 1) + ". " + t.name + " [" + mins + ":" + secs + "]");
      }
      return _results;
    })();
    trackText = tracks.join('\n');
    releaseStr = (_ref4 = releasedate.match(/\b\w+ (19|20)\d\d\b/)) != null ? _ref4[0] : void 0;
    insideText = releaseStr != null ? "Released: " + releaseStr : '';
    insideSize = 10;
    insideFlow = PDFText.preprocessPara(insideText, font);
    insidePara = PDFText.flowPara(insideFlow, insideSize, {
      maxWidth: fix(mm2pt(100))
    });
    numRe = /^(\d+)\.\s+/;
    durRe = /\s+\[(\d+:\d+)\]\s*$/;
    trackData = (function() {
      var _j, _len1, _ref5, _results;

      _ref5 = trackText.split('\n');
      _results = [];
      for (i = _j = 0, _len1 = _ref5.length; _j < _len1; i = ++_j) {
        t = _ref5[i];
        numMatch = t.match(numRe);
        num = numMatch != null ? numMatch[1] : void 0;
        durMatch = t.match(durRe);
        dur = durMatch != null ? durMatch[1] : void 0;
        name = t.replace(numRe, '').replace(durRe, '');
        _results.push({
          num: num,
          name: name,
          dur: dur
        });
      }
      return _results;
    })();
    fontObj = PDFFont.create(pdf, {
      name: font
    });
    fontBoldObj = PDFFont.create(pdf, {
      name: fontBold
    });
    mediaBox = "[0 " + (pageSizes.a4.h - pageSize.h) + " " + pageSize.w + " " + pageSizes.a4.h + "]";
    frontContent = PDFStream.create(pdf, {
      stream: "q  % colour block\n" + (bgCol.join(' ')) + " rg  % fill colour\n" + (fix(mm2pt(75))) + " " + (fix(pageSizes.a4.h - mm2pt(255))) + " " + (fix(mm2pt(120))) + " " + (fix(mm2pt(120))) + " re f  % rect, fill\nQ\n\nq  % small album art\n" + (fix(mm2pt(60))) + " 0 0 " + (fix(mm2pt(60))) + " " + (fix(mm2pt(165))) + " " + (fix(pageSizes.a4.h - mm2pt(225))) + " cm  % scaleX 0 0 scaleY trnslX trnslY cm\n0 1 -1 0 0 0 cm  % rotate 90deg a-cw\n/AlbumArt Do\nQ\n\nq  % line around small album art\n0.25 w  " + (fgCol.join(' ')) + " RG  % line colour\n" + (fix(mm2pt(105))) + " " + (fix(pageSizes.a4.h - mm2pt(225))) + " " + (fix(mm2pt(60))) + " " + (fix(mm2pt(60))) + " re  S  % rect, stroke\nQ\n\nq  % big album art\n" + (fix(mm2pt(120))) + " 0 0 " + (fix(mm2pt(120))) + " " + (fix(mm2pt(195))) + " " + (fix(pageSizes.a4.h - mm2pt(135))) + " cm  % scaleX 0 0 scaleY trnslX trnslY cm\n0 1 -1 0 0 0 cm  % rotate 90deg a-cw\n/AlbumArt Do\nQ\n\nq  % release date\n1 0 0 1 " + (fix(mm2pt(83))) + " " + (fix(pageSizes.a4.h - mm2pt(248))) + " cm  % scaleX 0 0 scaleY trnslX trnslY cm\n0 1 -1 0 0 0 cm  % rotate 90deg a-cw\nBT\n/Fnt " + insideSize + " Tf\n" + insidePara.commands + "\nET\nQ",
      minify: true
    });
    PDFObj.create(pdf, {
      data: "<<\n/Type /Page /Parent 3 0 R /Resources 6 0 R\n/Contents [" + frontContent.ref + " 4 0 R]\n/MediaBox " + mediaBox + "\n>>",
      num: 2
    });
    PDFObj.create(pdf, {
      data: "<<\n/ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ] /ColorSpace << /Cs1 7 0 R /Cs2 9 0 R >>\n/Font <<\n  /Tc3.0 11 0 R /Tc4.1 13 0 R /Tc2.0 10 0 R /TT5.1 15 0 R /Tc1.0 8 0 R /Tc6.0 16 0 R\n  /Fnt " + fontObj.ref + "\n  >>\n/XObject << /AlbumArt " + imgObj.ref + " >>\n>>",
      num: 6
    });
    artistPara = PDFText.preprocessPara(artist, font);
    namePara = PDFText.preprocessPara(albumName, fontBold);
    maxSpineWidth = mm2pt(100);
    spineXHeightFactor = font === 'Helvetica' ? 0.83 : 0.78;
    for (spineSize = _j = 10; _j >= 6; spineSize = --_j) {
      artistFlow = PDFText.flowPara(artistPara, spineSize, {
        lineHeight: 0
      });
      nameFlow = PDFText.flowPara(namePara, spineSize, {
        lineHeight: 0
      });
      spineSpace = spineSize * 0.5;
      totalWidth = artistFlow.width + spineSpace + nameFlow.width;
      if (totalWidth < maxSpineWidth) {
        break;
      }
    }
    spineCommands = "/Fnt " + spineSize + " Tf\n" + artistFlow.commands + "\n" + (artistFlow.width + spineSpace) + " 0 Td\n/FntBold " + spineSize + " Tf\n" + nameFlow.commands;
    maxTrackWidth = mm2pt(55);
    maxTrackHeight = mm2pt(87);
    for (_k = 0, _len1 = trackData.length; _k < _len1; _k++) {
      track = trackData[_k];
      for (k in track) {
        v = track[k];
        if (v != null) {
          track["" + k + "Para"] = PDFText.preprocessPara(v, font);
        }
      }
    }
    for (trackSize = _l = 10; _l >= 6; trackSize = --_l) {
      numAndDurSize = trackSize - 2;
      trackCommands = '';
      height = 0;
      trackSpacing = trackSize / 5;
      for (_m = 0, _len2 = trackData.length; _m < _len2; _m++) {
        track = trackData[_m];
        if (track.numPara) {
          numMaxWidth = numAndDurSize * 20;
          numFlow = PDFText.flowPara(track.numPara, numAndDurSize, {
            lineHeight: 0,
            align: 'right',
            maxWidth: numMaxWidth
          });
          trackCommands += "/Fnt " + numAndDurSize + " Tf\n" + (-numMaxWidth - trackSize) + " 0 Td\n" + numFlow.commands + "\n" + (numMaxWidth + trackSize) + " 0 Td\n";
        }
        if (track.durPara) {
          durMaxWidth = maxTrackWidth + numAndDurSize * 4.5;
          durFlow = PDFText.flowPara(track.durPara, numAndDurSize, {
            lineHeight: 0,
            align: 'right',
            maxWidth: durMaxWidth
          });
          trackCommands += "/Fnt " + numAndDurSize + " Tf\n" + durFlow.commands + "\n";
        }
        nameFlow = PDFText.flowPara(track.namePara, trackSize, {
          maxWidth: maxTrackWidth,
          lineHeight: 1.15
        });
        trackCommands += "/Fnt " + trackSize + " Tf\n" + nameFlow.commands + "\n0 " + (fix(-trackSpacing)) + " Td\n";
        height += nameFlow.height + trackSpacing;
      }
      if (height < maxTrackHeight) {
        break;
      }
    }
    backContent = PDFStream.create(pdf, {
      stream: "q  % colour block\n" + (bgCol.join(' ')) + " rg  % fill colour\n" + (fix(mm2pt(75))) + " " + (fix(pageSizes.a4.h - mm2pt(165))) + " " + (fix(mm2pt(117))) + " " + (fix(mm2pt(150))) + " re f  % rect, fill\nQ\n\nBT  % text down spine\n" + (fgCol.join(' ')) + " rg  % fill colour\n" + (fix(mm2pt(75) + (mm2pt(117) - totalWidth) / 2)) + " " + (fix(pageSizes.a4.h - mm2pt(15) - spineSize * spineXHeightFactor - (mm2pt(6.5) - spineSize) / 2)) + " Td\n" + spineCommands + "\n" + (fix(-artistFlow.width - spineSpace)) + " " + (fix(mm2pt(-143.5))) + " Td\n" + spineCommands + "\nET\n\nq  % track listing\n1 0 0 1 " + (fix(mm2pt(90))) + " " + (fix(pageSizes.a4.h - mm2pt(142))) + " cm  % scaleX 0 0 scaleY trnslX trnslY cm\n0 1 -1 0 0 0 cm  % rotate 90deg a-cw\nBT\n" + trackCommands + "\nET\nQ",
      minify: true
    });
    PDFObj.create(pdf, {
      data: "<<\n/Type /Page /Parent 3 0 R /Resources 24 0 R\n/Contents [" + backContent.ref + " 22 0 R]\n/MediaBox " + mediaBox + "\n>>",
      num: 21
    });
    PDFObj.create(pdf, {
      data: "<<\n/ProcSet [ /PDF /Text ] /ColorSpace << /Cs2 9 0 R /Cs1 7 0 R >>\n/Font <<\n  /Tc10.0 29 0 R /TT8.1 27 0 R /Tc7.0 25 0 R /Tc9.0 28 0 R\n  /Fnt " + fontObj.ref + " /FntBold " + fontBoldObj.ref + "\n  >>\n>>",
      num: 24
    });
    filename = ("" + artist + " " + albumName).toLowerCase().replace(/\s+/g, '_').replace(/\W+/g, '') + '.pdf';
    return pdf.linkAsync(filename, function(link) {
      link.appendChild(text('PDF'));
      return get({
        tag: 'body'
      }).appendChild(link);
    });
  });

  loadAssets();

}).call(this);

/*
//@ sourceMappingURL=cdcase.map
*/
